# Generated by Django 4.0.2 on 2022-03-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=300)),
                ('displayed_link', models.CharField(max_length=300)),
                ('snippet', models.CharField(max_length=300)),
            ],
        ),
    ]
